import os

def clean_temp_ndjson_file(file_path: str):
    """
    clean_temp_ndjson_file

    Deletes a specific NDJSON file if it exists. This is typically run after
    a successful S3 upload of the file generated by the LSF parsing pipeline.

    ----------------------------------------------------------------------------------------

    Parameters
    ----------
    - file_path : str
        Full local path to the NDJSON file to be deleted.

    ----------------------------------------------------------------------------------------

    Behavior
    --------
    - Deletes only the file at the provided path.
    - If the file does not exist, prints an info message.
    - If deletion fails, prints the error message.

    ----------------------------------------------------------------------------------------

    Example
    -------
    clean_temp_ndjson_file("/tmp/lsf_user_share_2025-06-12T18-45-00.ndjson")
    """
    if os.path.isfile(file_path):
        try:
            os.remove(file_path)
            print(f"[CLEANUP] Deleted temporary file: {file_path}")
        except Exception as e:
            print(f"[WARN] Could not delete file: {file_path} | Error: {e}")
    else:
        print(f"[INFO] No file to delete at: {file_path}")
